spring:
  application:
    name: discodeit
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  profiles:
    active: dev

discodeit:
  storage:
    type: ${STORAGE_TYPE:local} # local | s3
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:files}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers

info:
  app:
    name: Discodeit
    version: 1.7.0
  java: 17
  springboot: 3.4.2
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}