spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

discodeit:
  storage:
    type: local
    local:
      root-path: files

logging:
  level:
    root: info

info:
  app:
    name: Discodeit
    version: 1.7.0
  java: 17
  springboot: 3.4.2
  datasource:
    url: localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}