spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    database: postgresql
    open-in-view: false

discodeit:
  storage:
    local:
      root-path: files

logging:
  level:
    root: info