spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

discodeit:
  repository:
    type: file # jcf | file
    file-directory: .discodeit