name: CI teat

on:
  push:
    branches:
      - part3-허원재-sprint8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: chmod +x gradlew

      - name: Test
        run: ./gradlew test --no-daemon

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Oince/1-sprint-mission